### ISSUE TITLE
encounter problem

### ISSUE THREAD

**Issue by tianheg** [kda150230/Saved-Archiver-for-Reddit#1]
![Snipaste_2020-06-19_21-47-31](https://user-images.githubusercontent.com/52186032/85139214-af96c480-b276-11ea-8c75-a848df3783ad.jpg)

After click the url, it display this:

![Snipaste_2020-06-19_21-49-54](https://user-images.githubusercontent.com/52186032/85139327-d5bc6480-b276-11ea-898d-b216d203e195.jpg)

**Comment by tianheg** [comment]
env:

Python 3.8.2
PyCharm 2020.1.1 (Professional Edition)
Win10

**Comment by kylemaestro** [comment]
The socket error may be caused by insufficient privileges. Try starting powershell or cmd in administrative mode and manually starting the script by executing the command 'python archiver.py' in the folder containing the script. If you're getting errors with the sockets, the url the script gives you will almost certainly not be correct.
